### ISSUE TITLE
关于代码的调试

### ISSUE THREAD

**Issue by thewaterislo** [yaojh18/doudizhu#1]
请问这个代码在联机调试的时候是要多台电脑吗？请教你开发过程中的一些通信方面的调试是怎么方便点，我只有一台电脑 @yaojh18

**Comment by yaojh18** [comment]
在一台电脑上，不同的进程使用不同的端口就可以相互通信了。虽然使用一台电脑是进程间通信，不同电脑是网络通信，但是这个区别socket应该已经都帮你封装好了，只是使用API的话不会有任何区别。

**Comment by thewaterislo** [comment]
我决定改改，变成客户端服务端的模式，另外我发现qt的socket通信都是在事件循环里才会发，有点难受TAT
